### ISSUE TITLE
Implement global random seed

### ISSUE THREAD

**Issue by gogins** [gogins/athenaCL#1]
As per discussions with @tjingboem, implement a global random seed for athenaCL. This will involve one or more new athenaCL commands for setting the random seed with a custom value.

**Comment by gogins** [comment]
The main issue is that the random number generators in athenaCL come from OMDE. They are not regular athenaCL commands, but are used in various athenaCL commands. The following new Commands must be defined and they will use a singleton random seed.

[
[whishesAthenaCL.pdf](https://github.com/gogins/athenaCL/files/6290999/whishesAthenaCL.pdf)
](url)

**Comment by gogins** [comment]
Does each instance of the Python default RNG share the same seed? This I must know before I can proceed.

**Comment by gogins** [comment]
I misunderstood. There is only one default RNG and the UniformRG function in rand.py simply returns that singleton. So, we are virtually finished.

**Comment by tjingboem** [comment]
I believe (as described in wishesAthenaCL.pdf) 2 seeds should be
implemented. One is indeed for the rand.py from OMDE, and it concerns as
far as i can see the seed for all ParameterObject, while the second seed is
a seed for the TextureModules.
The latter is about choices being made in those TextureModules. The
TextureModules take the data from the Parameters and molds them to into
horizontal (note after note) or vertical (chords) patterns.  I *think *this
works like this: a TextureModule has a few parameters for this horizontal
or vertical molding, and they are called TextureStatic ParameterObjects
(C4. in the AthenaCL manual).  Here, again, some random stuff is going on
and each time the choice in this TextureModule is a bit different when no
seed for it is set.
This second seed value must be set to basePmtr.py line 171 etc..(as
described in wishesAthenaCL.pdf)

**Comment by gogins** [comment]
Yes, I agree with the above comment.

**Comment by gogins** [comment]
Is it better to have two separate random seeds for textures and parameter,
or it would be better to have just one random seed for both? Either one is
easy to do.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
I was thinking like this:
imagine you like very much the effect a seed value has on the ParameterObjects
but you hate what the TextureModule is doing to the pattern of the created TextureModule?

I see them as 2 different entities, so 2 "locally global" seeds are to be preferred.

But maybe i am mistaken.
I am having a hard time imagining one global seed for all, as i will never know what beautiful structures i will be missing if there would have been 2 different seeds.

 I will have to test it to confirm if it is nonsense to have 2 seeds instead of 1. 
I can do the testing with giving both seeds the same values for a while, and see what i am missing :)

Is implementing, as a test case, the option of 2 seeds a lot more work or is it better to start testing with only one seed?

**Comment by tjingboem** [comment]
i would say 2

**Comment by gogins** [comment]
I have installed blue and got the External soundObject and athenaPipe.py to
work with Python 3.9, the latest version. The sample athenaCL pieces in
blue are now rendering for me, so I have something to test with. If two
runs of the same piece with the same seed produce identical csd files, but
with no seed produce different csd files, it is working.

I am now working on the random seed changes.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
It is easier to do just one global random seed.

The problem is that the original athenaCL code sometimes uses the global random.random() function that already has a global random.seed() funcction, and sometimes creates a new random.Random() instance that will have its own individual seed, this is what the code in rand.py does.

Each RNG in rand.py is currently going to create its own instance of Random. This is not going to work very well. It means every parameter object will have to have its own seed set and this is not global at all.

This would be very easy to change and should not change the behavior of athenaCL in any way that would matter to the user.

**Comment by gogins** [comment]
I have reviewed this issue more extensively. It does not make sense to have a global preference for any random seeds, as these may and probably will differ between pieces. I have thus removed this Command.

**Comment by gogins** [comment]
I have implemented this and tested it with the attached blue project. Two different runs produce exactly the same .csd file.
[external_AthenaCL1.blue.txt](https://github.com/gogins/athenaCL/files/6305230/external_AthenaCL1.blue.txt)
